export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// async function getSession(cookie) {
//   const response = await fetch(
//     `${process.env.NEXT_PUBLIC_LOCAL_AUTH_URL}/api/auth/session`,
//     {
//       headers: {
//         cookie,
//       },
//     }
//   );

//   const session = await response.json();
//   return Object.keys(session).length > 0 ? session : null;
// }

export default async function RootLayout({ children, session }) {
  // const session = await getSession(headers().get("cookie") ?? "");
  // console.log(session);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
